export const MAKE_MOVE = "MAKE_MOVE";
export const FLIP_GAME_GRID = "FLIP_GAME_GRID";
export const RESTART_GAME = "RESTART_GAME";
export const UNDO_TURN = "UNDO_TURN";
export const REDO_TURN = "REDO_TURN";
export const TOGGLE_ICON_SELECT_OPEN = 'TOGGLE_ICON_SELECT_OPEN';
export const TOGGLE_ICON_SELECT_FLIPPED = 'TOGGLE_ICON_SELECT_FLIPPED';
export const UPDATE_ICON_INFO = 'UPDATE_ICON_INFO';
